# Generated by Django 5.2.1 on 2026-09-04 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0004_ownbasket_remove_ownfee_basketname_ownplan_basketid_and_more'),
        ('quickportal', '0033_remove_business_cnae'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory_name', models.CharField(max_length=200)),
                ('signatory_cpf', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.'), django.core.validators.MinLengthValidator(11)])),
                ('signatory_email', models.EmailField(max_length=254)),
                ('forecast_revenue', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('contract_revenue', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('postal_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.'), django.core.validators.MinLengthValidator(8)])),
                ('street', models.CharField(max_length=200)),
                ('address_number', models.CharField(max_length=20)),
                ('address_complement', models.CharField(blank=True, max_length=200)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\Z', 'Enter a two-letter state code.')])),
                ('pos_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bank_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.')])),
                ('bank_branch', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.')])),
                ('bank_branch_digit', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.')])),
                ('bank_account', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.')])),
                ('bank_account_digit', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.')])),
                ('core_protocol', models.CharField(blank=True, max_length=100)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='own_business', to='quickportal.business')),
                ('cnae', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='own.ownactivity')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='own.ownplan')),
            ],
            options={
                'db_table': 'own_businesses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OwnBusinessAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='own/businesses/')),
                ('original_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('COMPROVANTE_ENDERECO', 'Proof of address'), ('CONTRATO_SOCIAL', 'Articles of association'), ('TERMO_ADESAO', 'Adhesion term')], max_length=25)),
                ('own_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='own.ownbusiness')),
            ],
            options={
                'db_table': 'own_business_attachments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OwnBusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.'), django.core.validators.MinLengthValidator(11)])),
                ('own_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='own.ownbusiness')),
            ],
            options={
                'db_table': 'own_business_partners',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OwnPartnerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='own/partners/')),
                ('original_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RGFRENTE', 'ID front'), ('RGVERSO', 'ID back'), ('CPF', 'CPF'), ('CNH', 'Driver license'), ('COMPROVANTE_ENDERECO', 'Proof of address')], max_length=25)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='own.ownbusinesspartner')),
            ],
            options={
                'db_table': 'own_partner_attachments',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ownbusinesspartner',
            constraint=models.UniqueConstraint(fields=('own_business', 'cpf'), name='unique_own_business_partner_cpf'),
        ),
    ]
