# Generated by Django 5.2.1 on 2026-09-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0005_ownbusiness_ownbusinessattachment_ownbusinesspartner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownbusiness',
            name='registration_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ownbusiness',
            name='registration_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REGISTERED', 'Registered'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
