# Generated by Django 5.2.1 on 2026-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0012_ownbusiness_api_request_failed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownfee',
            name='method',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Debit', 'Debit'), ('Credit', 'Credit'), ('Installments', 'Installments'), ('POS Rent', 'POS Rent'), ('Top Bank', 'Top Bank'), ('Visa Voucher', 'Visa Voucher')], max_length=50),
        ),
    ]
