# Generated by Django 5.2.1 on 2026-09-10 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0013_alter_ownfee_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(choices=[('POS GPOS 700', 'POS GPOS 700'), ('POS GPOS 700 MINI', 'POS GPOS 700 MINI'), ('POS GPOS 760', 'POS GPOS 760'), ('POS IWL251', 'POS IWL251'), ('POS MOVE 2500', 'POS MOVE 2500'), ('POS PAX D195', 'POS PAX D195'), ('POS PAX Q92X', 'POS PAX Q92X'), ('POS PAX S920', 'POS PAX S920')], max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_own_pos', to=settings.AUTH_USER_MODEL)),
                ('own_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_devices', to='own.ownbusiness')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_own_pos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'own_pos',
                'ordering': ['id'],
            },
        ),
    ]
