# Generated by Django 5.2.1 on 2026-09-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0014_ownpos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownbusiness',
            name='cnae',
        ),
    ]
