# Generated by Django 5.2.1 on 2026-09-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0015_remove_ownbusiness_cnae'),
        ('quickportal', '0037_delete_acquirer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownplan',
            name='owner_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_plans', to='quickportal.business'),
        ),
        migrations.AlterField(
            model_name='ownfee',
            name='network',
            field=models.CharField(blank=True, choices=[('Visa', 'Visa'), ('Elo', 'Elo'), ('Mastercard', 'Mastercard')], max_length=50, null=True),
        ),
    ]
