# Generated by Django 5.2.1 on 2026-09-04 13:13

from django.db import migrations


# Existing generic CNAE values are intentionally discarded. Creating partial
# OWN registrations from them would violate the required signup data contract.


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0032_businesscolorpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='cnae',
        ),
    ]
