# Generated by Django 5.2.1 on 2026-09-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0034_remove_business_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='cnae',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='cnae',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='acquirer',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='network',
        ),
        migrations.RemoveField(
            model_name='planfee',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='acquirer',
        ),
        migrations.RemoveField(
            model_name='planfee',
            name='plan',
        ),
        migrations.DeleteModel(
            name='BusinessDetails',
        ),
        migrations.DeleteModel(
            name='Cnae',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanFee',
        ),
    ]
