# Generated by Django 5.2.1 on 2026-09-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0035_remove_fee_cnae_remove_plan_cnae_remove_fee_acquirer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posmodel',
            name='acquirer',
        ),
        migrations.DeleteModel(
            name='PosDevice',
        ),
        migrations.DeleteModel(
            name='PosModel',
        ),
    ]
