# Generated by Django 5.2.1 on 2026-09-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0036_remove_posmodel_acquirer_delete_posdevice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acquirer',
        ),
    ]
