# Generated by Django 5.2.1 on 2026-10-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0037_delete_acquirer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='document',
            field=models.CharField(error_messages={'unique': 'Este documento já está cadastrado.'}, max_length=20, unique=True),
        ),
    ]
