include:
  - ./quick-portal-api/docker-compose.dev.yml
  - ./quick-portal-web/docker-compose.dev.yml
  - ./quick-docs/docker-compose.dev.yml
  - ./mock-cielo/docker-compose.dev.yml

services:
  web:
    environment:
      CIELO_AUTH_BASE_URL: ${CIELO_AUTH_BASE_URL:-http://mock-cielo:3000}
      CIELO_ONBOARDING_BASE_URL: ${CIELO_ONBOARDING_BASE_URL:-http://mock-cielo:3000}
      CIELO_MERCHANT_ID: ${CIELO_MERCHANT_ID:-f88cc14d-c796-4939-957e-de4dddcb2257}
      CIELO_CLIENT_SECRET: ${CIELO_CLIENT_SECRET:-quick-portal-mock-secret}
    depends_on:
      mock-cielo:
        condition: service_healthy
