# Generated by Django 5.2.1 on 2026-09-24 13:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quickportal', '0037_delete_acquirer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CieloBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FAILED', 'Falhou'), ('PENDING', 'Pendente'), ('INTERVENTION_REQUIRED', 'Intervenção necessária')], max_length=30)),
                ('merchant_id', models.CharField(blank=True, max_length=36, null=True)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('contact_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('contact_name', models.CharField(max_length=100)),
                ('mail_address', models.EmailField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('document_number', models.CharField(max_length=14, unique=True)),
                ('corporate_name', models.CharField(max_length=100)),
                ('fancy_name', models.CharField(blank=True, max_length=50)),
                ('birthday_date', models.DateField(blank=True, null=True)),
                ('business_activity_id', models.CharField(blank=True, choices=[('1', 'Não encontrado'), ('2', 'Salão de beleza barbearia'), ('3', 'Dentistas e ortodontistas'), ('4', 'Lanchonete'), ('5', 'Vendas de roupas'), ('6', 'Taxi e limusine'), ('7', 'Mercearias e supermercados'), ('8', 'Lojas de variedades'), ('9', 'Bares discotecas casas noturnas'), ('10', 'Empreiteiros em geral'), ('11', 'Cosméticos'), ('12', 'Conveniência delicatessen'), ('13', 'Médicos e clínicas'), ('14', 'Serviços veterinários'), ('15', 'Lojas de reparos e serviços'), ('16', 'Comida rápida (doces e salgados)'), ('17', 'Diversão e recreação'), ('18', 'Creches'), ('19', 'Alfaiates / costureiras (os)'), ('20', 'Clínicas de beleza - spa'), ('21', 'Serviços legais'), ('22', 'Fabricação de máquinas, ferramentas, peças e acessórios'), ('23', 'Lojas de utensílios'), ('24', 'Restaurantes'), ('25', 'Peças e serviços para veículos'), ('26', 'Corretor imobiliário'), ('27', 'Fornecedores de alimentos ou mantimentos'), ('28', 'Conserto - rádio, tv, aparelho de som'), ('29', 'Presentes, cartões, souvenirs'), ('30', 'Lojas de acessórios para veículos'), ('31', 'Serviços de horticultura e jardinagem'), ('32', 'Lojas de material de construção'), ('33', 'Lojas de sapatos'), ('34', 'Joalherias e relojoarias'), ('35', 'Atacadista'), ('36', 'Serviços educacionais'), ('37', 'Padarias'), ('38', 'Lojas de bebidas'), ('39', 'Equipamentos e peças eletrônicas'), ('40', 'Consertos elétricos'), ('41', 'Borracheiro'), ('42', 'Drogarias farmácias'), ('43', 'Serviços de carpintaria'), ('44', 'Loja de animais'), ('45', 'Campo de esportes clubes'), ('46', 'Estúdio fotográfico'), ('47', 'Eletricista'), ('48', 'Transportes urbanos'), ('49', 'Laboratórios médicos dentários'), ('50', 'Docerias e confeitarias'), ('51', 'Lava rápido'), ('52', 'Mobilia e utilidades para o lar'), ('53', 'Laticínios'), ('54', 'Dança academias'), ('55', 'Serviços de manutenção e conservação'), ('56', 'Brinquedos e jogos'), ('57', 'Hotéis motéis'), ('58', 'Serviços de administração e consultoria'), ('59', 'Serviços de pesquisa para arquitetura e engenharia'), ('60', 'Banca de jornais'), ('61', 'Pedicure'), ('62', 'Lojas de departamento'), ('63', 'Floricultura'), ('64', 'Conserto e manutenção de computadores'), ('65', 'Materiais de construção'), ('66', 'Óticas'), ('67', 'Serviços escolares'), ('68', 'Casas de massagem'), ('69', 'Funilaria lanternagem'), ('70', 'Armarinhos tecidos'), ('71', 'Reparo e restauração de móveis'), ('72', 'Centros de serviços e oficinas de metal'), ('73', 'Conserto - joias e relógios'), ('74', 'Artigos de segunda mão'), ('75', 'Serviços de processamentos de dados'), ('76', 'Conserto de chapéus sapatos'), ('77', 'Livros, periódicos e jornais'), ('78', 'Cópias fotocópias'), ('79', 'Aluguel de roupas'), ('80', 'Lojas de ferragens'), ('81', 'Materiais de escritório'), ('82', 'Casas de repouso serviços de enfermagem'), ('83', 'Material esportivos'), ('84', 'Clubes atletismo - sócios'), ('85', 'Bicicletas - vendas e serviços'), ('86', 'Estacionamento de automóveis'), ('87', 'Escola vocação e ocupação'), ('88', 'Lojas de informática - software'), ('89', 'Papelarias'), ('90', 'Anúncios classificados propaganda'), ('91', 'Tapeçaria cortinas'), ('92', 'Rede de computadores provedores'), ('93', 'Aluguel de equipamentos e mobílias'), ('94', 'Organização religiosa'), ('95', 'Corretor de seguros'), ('96', 'Serviços de auditoria e contabilidade'), ('97', 'Galerias de arte leilão de arte'), ('98', 'Sapataria'), ('99', 'Tv a cabo, satélite, e outros tipos de tv'), ('100', 'Serviço de frete')], max_length=3, null=True)),
                ('bank', models.CharField(choices=[('001', 'Banco do Brasil'), ('003', 'Amazônia - BASA'), ('004', 'BNB'), ('012', 'BANCO INBURSA'), ('021', 'Est. ES - Banestes'), ('025', 'Alfa'), ('033', 'Santander'), ('037', 'Est. PA - Banpará'), ('041', 'Est. RS - Banrisul'), ('047', 'Est. SE - Banese'), ('063', 'BANCO BRADESCARD'), ('069', 'Banco Crefisa'), ('070', 'BRB - Banco de Brasília'), ('077', 'Banco Inter'), ('081', 'BANCOSEGURO S.A.'), ('082', 'Banco Topázio'), ('083', 'BCO DA CHINA BRASIL S.A.'), ('084', 'CC Uniprime Norte do Paraná'), ('085', 'CC Cecred'), ('089', 'CC Região da Mogiana'), ('093', 'POLOCRED SCMEPP LTDA.'), ('094', 'Banco Finaxis'), ('097', 'CC Centralcredi'), ('099', 'CC Uniprime Central'), ('102', 'XP INVESTIMENTOS CCTVM S/A'), ('104', 'Caixa Econômica Federal'), ('107', 'BBM'), ('120', 'Rodobens'), ('121', 'BCO AGIBANK S.A.'), ('125', 'BANCO GENIAL'), ('130', 'Scfi Caruana'), ('133', 'CRESOL CONFEDERAÇÃO'), ('136', 'CC Unicred do Brasil'), ('149', 'FACTA S.A. CFI'), ('174', 'PEFISA S.A. - C.F.I.'), ('195', 'VALOR SCD S.A.'), ('197', 'STONE PAGAMENTOS S.A'), ('208', 'BANCO BTG PACTUAL S.A'), ('212', 'Banco Original'), ('213', 'Arbi'), ('218', 'Banco BS2'), ('224', 'Fibra'), ('237', 'Bradesco'), ('243', 'Banco Master'), ('246', 'ABC - Brasil'), ('260', 'NU PAGAMENTOS S.A (NUBANK)'), ('274', 'Money Plus SCMEPP LTDA'), ('299', 'BCO SOROCRED S.A. - BM'), ('301', 'Dock Instituição de Pagamento S.A'), ('318', 'BCO BMG S.A.'), ('320', 'BCO CCB BRASIL S.A.'), ('323', 'Mercado Pago'), ('329', 'QI SCD S.A.'), ('330', 'BANCO BARI S.A.'), ('335', 'Banco Digio S.A.'), ('336', 'Banco C6 S.A'), ('341', 'Itaú Unibanco'), ('348', 'BCO XP S.A.'), ('359', 'ZEMA CFI S/A'), ('364', 'GERENCIANET'), ('368', 'BCO CSF S.A.'), ('376', 'J. P. Morgan'), ('380', 'PICPAY'), ('382', 'FIDUCIA SCMEPP LTDA'), ('383', 'JUNO'), ('389', 'Mercantil do Brasil'), ('394', 'BCO BRADESCO FINANC. S.A.'), ('396', 'HUB PAGAMENTOS'), ('403', 'CORA SCD S.A.'), ('404', 'SUMUP SCD S.A.'), ('406', 'ACCREDITO SCD S.A.'), ('413', 'BCO BV S.A.'), ('414', 'WORK SCD S.A.'), ('422', 'Safra'), ('435', 'DELCRED SCD S.A.'), ('450', 'FITBANK PAGAMENTOS ELETRONICOS S.A.'), ('477', 'CITIBANK N.A.'), ('487', 'DEUTSCHE BANK S.A.BCO ALEMAO'), ('542', 'Cloud Walk Meios de Pagamentos'), ('595', 'Zoop Instituição de Pagamentos'), ('600', 'Luso Brasileiro'), ('604', 'Indl. do Brasil'), ('611', 'Paulista'), ('612', 'Guanabara'), ('613', 'OMNI BANCO S.A.'), ('623', 'BANCO PAN'), ('630', 'Banco Smartbank'), ('633', 'Rendimento'), ('634', 'Triângulo'), ('637', 'Sofisa'), ('643', 'Pine'), ('653', 'BANCO VOITER'), ('654', 'Banco Digimais'), ('655', 'Votorantim'), ('707', 'Daycoval'), ('741', 'Ribeirão Preto'), ('743', 'Semear'), ('745', 'Citibank S. A.'), ('748', 'Sicredi'), ('752', 'BCO BNP PARIBAS BRASIL S A'), ('753', 'NOVO BCO CONTINENTAL S.A. - BM'), ('755', 'Bank of America Merrill Lynch'), ('756', 'Bancoob - Banco Cooperativo do Brasil (Sicoob)'), ('757', 'BCO KEB HANA DO BRASIL S.A.')], max_length=3)),
                ('bank_account_type', models.CharField(choices=[('CheckingAccount', 'Conta corrente'), ('SavingsAccount', 'Conta poupança')], max_length=20)),
                ('bank_account_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('bank_account_verifier_digit', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('bank_agency_number', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('bank_agency_digit', models.CharField(max_length=1)),
                ('bank_document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('bank_document_number', models.CharField(max_length=14)),
                ('address_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('address_complement', models.CharField(blank=True, max_length=80)),
                ('address_zip_code', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('address_street', models.CharField(max_length=100)),
                ('address_neighborhood', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cielo_business', to='quickportal.business')),
            ],
            options={
                'db_table': 'cielo_businesses',
            },
        ),
    ]
