# Generated by Django 5.2.1 on 2026-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cielobusiness',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='cielobusiness',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='cielobusiness',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='cielobusiness',
            name='mail_address',
        ),
        migrations.AlterField(
            model_name='cielobusiness',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
