# Generated by Django 5.2.1 on 2026-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0002_remove_cielobusiness_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cielobusiness',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
