# Generated by Django 5.2.1 on 2026-09-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0003_alter_cielobusiness_corporate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cielobusiness',
            name='bank_agency_digit',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
