# Generated by Django 5.2.1 on 2026-09-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0004_alter_cielobusiness_bank_agency_digit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cielobusiness',
            name='bank_account_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Erro interno'), (1, 'Criado'), (2, 'Em processamento'), (3, 'Sucesso'), (4, 'Erro')], null=True),
        ),
        migrations.AddField(
            model_name='cielobusiness',
            name='bank_account_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cielobusiness',
            name='kyc_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Em análise'), (2, 'Aprovado'), (3, 'Aprovado com restrição'), (4, 'Rejeitado')], null=True),
        ),
        migrations.AddField(
            model_name='cielobusiness',
            name='kyc_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cielobusiness',
            name='onboarding_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Em análise'), (2, 'Aprovado'), (3, 'Aguardando ação do lojista'), (4, 'Desconhecido'), (5, 'Banido')], null=True),
        ),
        migrations.AddField(
            model_name='cielobusiness',
            name='onboarding_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cielobusiness',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cielobusiness',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Falhou'), ('SENT', 'Enviado'), ('INTERVENTION_REQUIRED', 'Intervenção necessária')], max_length=30),
        ),
        migrations.CreateModel(
            name='CieloNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.PositiveSmallIntegerField(choices=[(20, 'KYC'), (21, 'Conta bancária'), (23, 'Credenciamento')])),
                ('merchant_id', models.CharField(max_length=36)),
                ('kyc_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Em análise'), (2, 'Aprovado'), (3, 'Aprovado com restrição'), (4, 'Rejeitado')], null=True)),
                ('bank_account_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Erro interno'), (1, 'Criado'), (2, 'Em processamento'), (3, 'Sucesso'), (4, 'Erro')], null=True)),
                ('onboarding_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Em análise'), (2, 'Aprovado'), (3, 'Aguardando ação do lojista'), (4, 'Desconhecido'), (5, 'Banido')], null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('cielo_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='cielo.cielobusiness')),
            ],
            options={
                'db_table': 'cielo_notifications',
            },
        ),
    ]
