# Generated by Django 5.2.1 on 2026-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0005_cielobusiness_bank_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cielonotification',
            name='bank_account_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cielonotification',
            name='kyc_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cielonotification',
            name='onboarding_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
