# Generated by Django 5.2.1 on 2026-10-02 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0006_alter_cielonotification_bank_account_status_and_more'),
        ('quickportal', '0037_delete_acquirer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CieloPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_cielo_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cielo_plans', to=settings.AUTH_USER_MODEL)),
                ('owner_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cielo_plans', to='quickportal.business')),
            ],
            options={
                'db_table': 'cielo_plans',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cielobusiness',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to='cielo.cieloplan'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CieloPlanRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_brand', models.CharField(choices=[('Visa', 'Visa'), ('Elo', 'Elo'), ('MasterCard', 'MasterCard')], max_length=20)),
                ('method', models.CharField(choices=[('Credit', 'Crédito'), ('Debit', 'Débito')], max_length=10)),
                ('installments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mdr', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fixed_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='cielo.cieloplan')),
            ],
            options={
                'db_table': 'cielo_plan_rates',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cieloplan',
            constraint=models.UniqueConstraint(fields=('owner_business', 'name'), name='unique_cielo_plan_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='cieloplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True)), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False)), _connector='OR'), name='cielo_plan_archived_at_and_by_together'),
        ),
        migrations.AddConstraint(
            model_name='cieloplanrate',
            constraint=models.UniqueConstraint(fields=('plan', 'card_brand', 'method', 'installments'), name='unique_cielo_plan_rate', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='cieloplanrate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('installments__isnull', True), ('method', 'Debit')), models.Q(('installments__gte', 1), ('installments__lte', 12), ('method', 'Credit')), _connector='OR'), name='cielo_plan_rate_installments_match_method'),
        ),
        migrations.AddConstraint(
            model_name='cieloplanrate',
            constraint=models.CheckConstraint(condition=models.Q(('mdr__gte', 0), ('mdr__lte', 100)), name='cielo_plan_rate_mdr_range'),
        ),
        migrations.AddConstraint(
            model_name='cieloplanrate',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_fee__gte', 0)), name='cielo_plan_rate_fixed_fee_not_negative'),
        ),
    ]
