# Generated by Django 5.2.1 on 2026-10-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0007_cieloplan_cielobusiness_plan_cieloplanrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CieloOnboardingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.PositiveSmallIntegerField(choices=[(20, 'KYC'), (21, 'Conta bancária'), (23, 'Credenciamento')])),
                ('merchant_id', models.CharField(max_length=36)),
                ('kyc_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bank_account_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('onboarding_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('cielo_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_notifications', to='cielo.cielobusiness')),
            ],
            options={
                'db_table': 'cielo_onboarding_notifications',
            },
        ),
        migrations.DeleteModel(
            name='CieloNotification',
        ),
    ]
