# Generated by Django 5.2.1 on 2026-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0008_cieloonboardingnotification_delete_cielonotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cieloplanrate',
            name='card_brand',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Elo', 'Elo'), ('Master', 'Master')], max_length=20),
        ),
    ]
