# Generated by Django 5.2.1 on 2026-10-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0009_alter_cieloplanrate_card_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CieloTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=36, unique=True)),
                ('merchant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('installments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('CreditCard', 'Crédito'), ('DebitCard', 'Débito'), ('SplittedCreditCard', 'Crédito'), ('SplittedDebitCard', 'Débito'), ('Pix', 'Pix'), ('Boleto', 'Boleto')], max_length=40, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('provider', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Não finalizado'), (1, 'Autorizado'), (2, 'Pago'), (3, 'Negado'), (10, 'Cancelado'), (11, 'Estornado'), (12, 'Pendente'), (13, 'Abortado'), (20, 'Agendado')], null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('lookup_status', models.CharField(blank=True, choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falhou')], max_length=10, null=True)),
                ('last_lookup_at', models.DateTimeField(blank=True, null=True)),
                ('lookup_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cielo_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cielo.cielobusiness')),
            ],
            options={
                'db_table': 'cielo_transactions',
            },
        ),
        migrations.CreateModel(
            name='CieloTransactionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=36)),
                ('change_type', models.PositiveSmallIntegerField(choices=[(1, 'Mudança de status do pagamento'), (2, 'Recorrência criada'), (3, 'Mudança de status do antifraude'), (4, 'Mudança de status da recorrência'), (5, 'Cancelamento negado'), (6, 'Boleto pago a menor'), (7, 'Chargeback'), (8, 'Alerta de fraude'), (25, 'Cancelamento parcial')])),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='cielo.cielotransaction')),
            ],
            options={
                'db_table': 'cielo_transaction_notifications',
            },
        ),
    ]
