/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRoutesRouteRouteImport } from './routes/_authRoutes/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRoutesSalesRouteImport } from './routes/_authRoutes/sales'
import { Route as AuthRoutesRecurringFeesRouteImport } from './routes/_authRoutes/recurring-fees'
import { Route as AuthRoutesPlanosETaxasRouteImport } from './routes/_authRoutes/planos-e-taxas'
import { Route as AuthRoutesNovoPlanoRouteImport } from './routes/_authRoutes/novo-plano'
import { Route as AuthRoutesNovoEcRouteImport } from './routes/_authRoutes/novo-ec'
import { Route as AuthRoutesBusinessListRouteImport } from './routes/_authRoutes/business-list'
import { Route as AuthRoutesRecurringFeesIndexRouteImport } from './routes/_authRoutes/recurring-fees.index'
import { Route as AuthRoutesBusinessListIdRouteImport } from './routes/_authRoutes/business-list_.$id'
import { Route as AuthRoutesRecurringFeesNewTargetsRouteImport } from './routes/_authRoutes/recurring-fees.new.targets'
import { Route as AuthRoutesRecurringFeesNewScheduleRouteImport } from './routes/_authRoutes/recurring-fees.new.schedule'
import { Route as AuthRoutesRecurringFeesNewReviewRouteImport } from './routes/_authRoutes/recurring-fees.new.review'
import { Route as AuthRoutesRecurringFeesNewPricingRouteImport } from './routes/_authRoutes/recurring-fees.new.pricing'
import { Route as AuthRoutesRecurringFeesNewDetailsRouteImport } from './routes/_authRoutes/recurring-fees.new.details'
import { Route as AuthRoutesBusinessListIdCredenciamentoOwnRouteImport } from './routes/_authRoutes/business-list_.$id_.credenciamento-own'
import { Route as AuthRoutesBusinessListIdCredenciamentoCieloRouteImport } from './routes/_authRoutes/business-list_.$id_.credenciamento-cielo'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoutesRouteRoute = AuthRoutesRouteRouteImport.update({
  id: '/_authRoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoutesSalesRoute = AuthRoutesSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesRecurringFeesRoute = AuthRoutesRecurringFeesRouteImport.update({
  id: '/recurring-fees',
  path: '/recurring-fees',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesPlanosETaxasRoute = AuthRoutesPlanosETaxasRouteImport.update({
  id: '/planos-e-taxas',
  path: '/planos-e-taxas',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesNovoPlanoRoute = AuthRoutesNovoPlanoRouteImport.update({
  id: '/novo-plano',
  path: '/novo-plano',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesNovoEcRoute = AuthRoutesNovoEcRouteImport.update({
  id: '/novo-ec',
  path: '/novo-ec',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesBusinessListRoute = AuthRoutesBusinessListRouteImport.update({
  id: '/business-list',
  path: '/business-list',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesRecurringFeesIndexRoute =
  AuthRoutesRecurringFeesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthRoutesRecurringFeesRoute,
  } as any)
const AuthRoutesBusinessListIdRoute =
  AuthRoutesBusinessListIdRouteImport.update({
    id: '/business-list_/$id',
    path: '/business-list/$id',
    getParentRoute: () => AuthRoutesRouteRoute,
  } as any)
const AuthRoutesRecurringFeesNewTargetsRoute =
  AuthRoutesRecurringFeesNewTargetsRouteImport.update({
    id: '/new/targets',
    path: '/new/targets',
    getParentRoute: () => AuthRoutesRecurringFeesRoute,
  } as any)
const AuthRoutesRecurringFeesNewScheduleRoute =
  AuthRoutesRecurringFeesNewScheduleRouteImport.update({
    id: '/new/schedule',
    path: '/new/schedule',
    getParentRoute: () => AuthRoutesRecurringFeesRoute,
  } as any)
const AuthRoutesRecurringFeesNewReviewRoute =
  AuthRoutesRecurringFeesNewReviewRouteImport.update({
    id: '/new/review',
    path: '/new/review',
    getParentRoute: () => AuthRoutesRecurringFeesRoute,
  } as any)
const AuthRoutesRecurringFeesNewPricingRoute =
  AuthRoutesRecurringFeesNewPricingRouteImport.update({
    id: '/new/pricing',
    path: '/new/pricing',
    getParentRoute: () => AuthRoutesRecurringFeesRoute,
  } as any)
const AuthRoutesRecurringFeesNewDetailsRoute =
  AuthRoutesRecurringFeesNewDetailsRouteImport.update({
    id: '/new/details',
    path: '/new/details',
    getParentRoute: () => AuthRoutesRecurringFeesRoute,
  } as any)
const AuthRoutesBusinessListIdCredenciamentoOwnRoute =
  AuthRoutesBusinessListIdCredenciamentoOwnRouteImport.update({
    id: '/business-list_/$id_/credenciamento-own',
    path: '/business-list/$id/credenciamento-own',
    getParentRoute: () => AuthRoutesRouteRoute,
  } as any)
const AuthRoutesBusinessListIdCredenciamentoCieloRoute =
  AuthRoutesBusinessListIdCredenciamentoCieloRouteImport.update({
    id: '/business-list_/$id_/credenciamento-cielo',
    path: '/business-list/$id/credenciamento-cielo',
    getParentRoute: () => AuthRoutesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/business-list': typeof AuthRoutesBusinessListRoute
  '/novo-ec': typeof AuthRoutesNovoEcRoute
  '/novo-plano': typeof AuthRoutesNovoPlanoRoute
  '/planos-e-taxas': typeof AuthRoutesPlanosETaxasRoute
  '/recurring-fees': typeof AuthRoutesRecurringFeesRouteWithChildren
  '/sales': typeof AuthRoutesSalesRoute
  '/business-list/$id': typeof AuthRoutesBusinessListIdRoute
  '/recurring-fees/': typeof AuthRoutesRecurringFeesIndexRoute
  '/business-list/$id/credenciamento-cielo': typeof AuthRoutesBusinessListIdCredenciamentoCieloRoute
  '/business-list/$id/credenciamento-own': typeof AuthRoutesBusinessListIdCredenciamentoOwnRoute
  '/recurring-fees/new/details': typeof AuthRoutesRecurringFeesNewDetailsRoute
  '/recurring-fees/new/pricing': typeof AuthRoutesRecurringFeesNewPricingRoute
  '/recurring-fees/new/review': typeof AuthRoutesRecurringFeesNewReviewRoute
  '/recurring-fees/new/schedule': typeof AuthRoutesRecurringFeesNewScheduleRoute
  '/recurring-fees/new/targets': typeof AuthRoutesRecurringFeesNewTargetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/business-list': typeof AuthRoutesBusinessListRoute
  '/novo-ec': typeof AuthRoutesNovoEcRoute
  '/novo-plano': typeof AuthRoutesNovoPlanoRoute
  '/planos-e-taxas': typeof AuthRoutesPlanosETaxasRoute
  '/sales': typeof AuthRoutesSalesRoute
  '/business-list/$id': typeof AuthRoutesBusinessListIdRoute
  '/recurring-fees': typeof AuthRoutesRecurringFeesIndexRoute
  '/business-list/$id/credenciamento-cielo': typeof AuthRoutesBusinessListIdCredenciamentoCieloRoute
  '/business-list/$id/credenciamento-own': typeof AuthRoutesBusinessListIdCredenciamentoOwnRoute
  '/recurring-fees/new/details': typeof AuthRoutesRecurringFeesNewDetailsRoute
  '/recurring-fees/new/pricing': typeof AuthRoutesRecurringFeesNewPricingRoute
  '/recurring-fees/new/review': typeof AuthRoutesRecurringFeesNewReviewRoute
  '/recurring-fees/new/schedule': typeof AuthRoutesRecurringFeesNewScheduleRoute
  '/recurring-fees/new/targets': typeof AuthRoutesRecurringFeesNewTargetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authRoutes': typeof AuthRoutesRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authRoutes/business-list': typeof AuthRoutesBusinessListRoute
  '/_authRoutes/novo-ec': typeof AuthRoutesNovoEcRoute
  '/_authRoutes/novo-plano': typeof AuthRoutesNovoPlanoRoute
  '/_authRoutes/planos-e-taxas': typeof AuthRoutesPlanosETaxasRoute
  '/_authRoutes/recurring-fees': typeof AuthRoutesRecurringFeesRouteWithChildren
  '/_authRoutes/sales': typeof AuthRoutesSalesRoute
  '/_authRoutes/business-list_/$id': typeof AuthRoutesBusinessListIdRoute
  '/_authRoutes/recurring-fees/': typeof AuthRoutesRecurringFeesIndexRoute
  '/_authRoutes/business-list_/$id_/credenciamento-cielo': typeof AuthRoutesBusinessListIdCredenciamentoCieloRoute
  '/_authRoutes/business-list_/$id_/credenciamento-own': typeof AuthRoutesBusinessListIdCredenciamentoOwnRoute
  '/_authRoutes/recurring-fees/new/details': typeof AuthRoutesRecurringFeesNewDetailsRoute
  '/_authRoutes/recurring-fees/new/pricing': typeof AuthRoutesRecurringFeesNewPricingRoute
  '/_authRoutes/recurring-fees/new/review': typeof AuthRoutesRecurringFeesNewReviewRoute
  '/_authRoutes/recurring-fees/new/schedule': typeof AuthRoutesRecurringFeesNewScheduleRoute
  '/_authRoutes/recurring-fees/new/targets': typeof AuthRoutesRecurringFeesNewTargetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/business-list'
    | '/novo-ec'
    | '/novo-plano'
    | '/planos-e-taxas'
    | '/recurring-fees'
    | '/sales'
    | '/business-list/$id'
    | '/recurring-fees/'
    | '/business-list/$id/credenciamento-cielo'
    | '/business-list/$id/credenciamento-own'
    | '/recurring-fees/new/details'
    | '/recurring-fees/new/pricing'
    | '/recurring-fees/new/review'
    | '/recurring-fees/new/schedule'
    | '/recurring-fees/new/targets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/business-list'
    | '/novo-ec'
    | '/novo-plano'
    | '/planos-e-taxas'
    | '/sales'
    | '/business-list/$id'
    | '/recurring-fees'
    | '/business-list/$id/credenciamento-cielo'
    | '/business-list/$id/credenciamento-own'
    | '/recurring-fees/new/details'
    | '/recurring-fees/new/pricing'
    | '/recurring-fees/new/review'
    | '/recurring-fees/new/schedule'
    | '/recurring-fees/new/targets'
  id:
    | '__root__'
    | '/'
    | '/_authRoutes'
    | '/signup'
    | '/_authRoutes/business-list'
    | '/_authRoutes/novo-ec'
    | '/_authRoutes/novo-plano'
    | '/_authRoutes/planos-e-taxas'
    | '/_authRoutes/recurring-fees'
    | '/_authRoutes/sales'
    | '/_authRoutes/business-list_/$id'
    | '/_authRoutes/recurring-fees/'
    | '/_authRoutes/business-list_/$id_/credenciamento-cielo'
    | '/_authRoutes/business-list_/$id_/credenciamento-own'
    | '/_authRoutes/recurring-fees/new/details'
    | '/_authRoutes/recurring-fees/new/pricing'
    | '/_authRoutes/recurring-fees/new/review'
    | '/_authRoutes/recurring-fees/new/schedule'
    | '/_authRoutes/recurring-fees/new/targets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoutesRouteRoute: typeof AuthRoutesRouteRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authRoutes': {
      id: '/_authRoutes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authRoutes/sales': {
      id: '/_authRoutes/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthRoutesSalesRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/recurring-fees': {
      id: '/_authRoutes/recurring-fees'
      path: '/recurring-fees'
      fullPath: '/recurring-fees'
      preLoaderRoute: typeof AuthRoutesRecurringFeesRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/planos-e-taxas': {
      id: '/_authRoutes/planos-e-taxas'
      path: '/planos-e-taxas'
      fullPath: '/planos-e-taxas'
      preLoaderRoute: typeof AuthRoutesPlanosETaxasRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/novo-plano': {
      id: '/_authRoutes/novo-plano'
      path: '/novo-plano'
      fullPath: '/novo-plano'
      preLoaderRoute: typeof AuthRoutesNovoPlanoRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/novo-ec': {
      id: '/_authRoutes/novo-ec'
      path: '/novo-ec'
      fullPath: '/novo-ec'
      preLoaderRoute: typeof AuthRoutesNovoEcRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/business-list': {
      id: '/_authRoutes/business-list'
      path: '/business-list'
      fullPath: '/business-list'
      preLoaderRoute: typeof AuthRoutesBusinessListRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/recurring-fees/': {
      id: '/_authRoutes/recurring-fees/'
      path: '/'
      fullPath: '/recurring-fees/'
      preLoaderRoute: typeof AuthRoutesRecurringFeesIndexRouteImport
      parentRoute: typeof AuthRoutesRecurringFeesRoute
    }
    '/_authRoutes/business-list_/$id': {
      id: '/_authRoutes/business-list_/$id'
      path: '/business-list/$id'
      fullPath: '/business-list/$id'
      preLoaderRoute: typeof AuthRoutesBusinessListIdRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/recurring-fees/new/targets': {
      id: '/_authRoutes/recurring-fees/new/targets'
      path: '/new/targets'
      fullPath: '/recurring-fees/new/targets'
      preLoaderRoute: typeof AuthRoutesRecurringFeesNewTargetsRouteImport
      parentRoute: typeof AuthRoutesRecurringFeesRoute
    }
    '/_authRoutes/recurring-fees/new/schedule': {
      id: '/_authRoutes/recurring-fees/new/schedule'
      path: '/new/schedule'
      fullPath: '/recurring-fees/new/schedule'
      preLoaderRoute: typeof AuthRoutesRecurringFeesNewScheduleRouteImport
      parentRoute: typeof AuthRoutesRecurringFeesRoute
    }
    '/_authRoutes/recurring-fees/new/review': {
      id: '/_authRoutes/recurring-fees/new/review'
      path: '/new/review'
      fullPath: '/recurring-fees/new/review'
      preLoaderRoute: typeof AuthRoutesRecurringFeesNewReviewRouteImport
      parentRoute: typeof AuthRoutesRecurringFeesRoute
    }
    '/_authRoutes/recurring-fees/new/pricing': {
      id: '/_authRoutes/recurring-fees/new/pricing'
      path: '/new/pricing'
      fullPath: '/recurring-fees/new/pricing'
      preLoaderRoute: typeof AuthRoutesRecurringFeesNewPricingRouteImport
      parentRoute: typeof AuthRoutesRecurringFeesRoute
    }
    '/_authRoutes/recurring-fees/new/details': {
      id: '/_authRoutes/recurring-fees/new/details'
      path: '/new/details'
      fullPath: '/recurring-fees/new/details'
      preLoaderRoute: typeof AuthRoutesRecurringFeesNewDetailsRouteImport
      parentRoute: typeof AuthRoutesRecurringFeesRoute
    }
    '/_authRoutes/business-list_/$id_/credenciamento-own': {
      id: '/_authRoutes/business-list_/$id_/credenciamento-own'
      path: '/business-list/$id/credenciamento-own'
      fullPath: '/business-list/$id/credenciamento-own'
      preLoaderRoute: typeof AuthRoutesBusinessListIdCredenciamentoOwnRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/business-list_/$id_/credenciamento-cielo': {
      id: '/_authRoutes/business-list_/$id_/credenciamento-cielo'
      path: '/business-list/$id/credenciamento-cielo'
      fullPath: '/business-list/$id/credenciamento-cielo'
      preLoaderRoute: typeof AuthRoutesBusinessListIdCredenciamentoCieloRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
  }
}

interface AuthRoutesRecurringFeesRouteChildren {
  AuthRoutesRecurringFeesIndexRoute: typeof AuthRoutesRecurringFeesIndexRoute
  AuthRoutesRecurringFeesNewDetailsRoute: typeof AuthRoutesRecurringFeesNewDetailsRoute
  AuthRoutesRecurringFeesNewPricingRoute: typeof AuthRoutesRecurringFeesNewPricingRoute
  AuthRoutesRecurringFeesNewReviewRoute: typeof AuthRoutesRecurringFeesNewReviewRoute
  AuthRoutesRecurringFeesNewScheduleRoute: typeof AuthRoutesRecurringFeesNewScheduleRoute
  AuthRoutesRecurringFeesNewTargetsRoute: typeof AuthRoutesRecurringFeesNewTargetsRoute
}

const AuthRoutesRecurringFeesRouteChildren: AuthRoutesRecurringFeesRouteChildren =
  {
    AuthRoutesRecurringFeesIndexRoute: AuthRoutesRecurringFeesIndexRoute,
    AuthRoutesRecurringFeesNewDetailsRoute:
      AuthRoutesRecurringFeesNewDetailsRoute,
    AuthRoutesRecurringFeesNewPricingRoute:
      AuthRoutesRecurringFeesNewPricingRoute,
    AuthRoutesRecurringFeesNewReviewRoute:
      AuthRoutesRecurringFeesNewReviewRoute,
    AuthRoutesRecurringFeesNewScheduleRoute:
      AuthRoutesRecurringFeesNewScheduleRoute,
    AuthRoutesRecurringFeesNewTargetsRoute:
      AuthRoutesRecurringFeesNewTargetsRoute,
  }

const AuthRoutesRecurringFeesRouteWithChildren =
  AuthRoutesRecurringFeesRoute._addFileChildren(
    AuthRoutesRecurringFeesRouteChildren,
  )

interface AuthRoutesRouteRouteChildren {
  AuthRoutesBusinessListRoute: typeof AuthRoutesBusinessListRoute
  AuthRoutesNovoEcRoute: typeof AuthRoutesNovoEcRoute
  AuthRoutesNovoPlanoRoute: typeof AuthRoutesNovoPlanoRoute
  AuthRoutesPlanosETaxasRoute: typeof AuthRoutesPlanosETaxasRoute
  AuthRoutesRecurringFeesRoute: typeof AuthRoutesRecurringFeesRouteWithChildren
  AuthRoutesSalesRoute: typeof AuthRoutesSalesRoute
  AuthRoutesBusinessListIdRoute: typeof AuthRoutesBusinessListIdRoute
  AuthRoutesBusinessListIdCredenciamentoCieloRoute: typeof AuthRoutesBusinessListIdCredenciamentoCieloRoute
  AuthRoutesBusinessListIdCredenciamentoOwnRoute: typeof AuthRoutesBusinessListIdCredenciamentoOwnRoute
}

const AuthRoutesRouteRouteChildren: AuthRoutesRouteRouteChildren = {
  AuthRoutesBusinessListRoute: AuthRoutesBusinessListRoute,
  AuthRoutesNovoEcRoute: AuthRoutesNovoEcRoute,
  AuthRoutesNovoPlanoRoute: AuthRoutesNovoPlanoRoute,
  AuthRoutesPlanosETaxasRoute: AuthRoutesPlanosETaxasRoute,
  AuthRoutesRecurringFeesRoute: AuthRoutesRecurringFeesRouteWithChildren,
  AuthRoutesSalesRoute: AuthRoutesSalesRoute,
  AuthRoutesBusinessListIdRoute: AuthRoutesBusinessListIdRoute,
  AuthRoutesBusinessListIdCredenciamentoCieloRoute:
    AuthRoutesBusinessListIdCredenciamentoCieloRoute,
  AuthRoutesBusinessListIdCredenciamentoOwnRoute:
    AuthRoutesBusinessListIdCredenciamentoOwnRoute,
}

const AuthRoutesRouteRouteWithChildren = AuthRoutesRouteRoute._addFileChildren(
  AuthRoutesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoutesRouteRoute: AuthRoutesRouteRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
