/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRoutesRouteRouteImport } from './routes/_authRoutes/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRoutesNovoEcRouteImport } from './routes/_authRoutes/novo-ec'
import { Route as AuthRoutesHomeRouteImport } from './routes/_authRoutes/home'
import { Route as AuthRoutesCompletarEcRouteImport } from './routes/_authRoutes/completar-ec'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoutesRouteRoute = AuthRoutesRouteRouteImport.update({
  id: '/_authRoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoutesNovoEcRoute = AuthRoutesNovoEcRouteImport.update({
  id: '/novo-ec',
  path: '/novo-ec',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesHomeRoute = AuthRoutesHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesCompletarEcRoute = AuthRoutesCompletarEcRouteImport.update({
  id: '/completar-ec',
  path: '/completar-ec',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/completar-ec': typeof AuthRoutesCompletarEcRoute
  '/home': typeof AuthRoutesHomeRoute
  '/novo-ec': typeof AuthRoutesNovoEcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/completar-ec': typeof AuthRoutesCompletarEcRoute
  '/home': typeof AuthRoutesHomeRoute
  '/novo-ec': typeof AuthRoutesNovoEcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authRoutes': typeof AuthRoutesRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authRoutes/completar-ec': typeof AuthRoutesCompletarEcRoute
  '/_authRoutes/home': typeof AuthRoutesHomeRoute
  '/_authRoutes/novo-ec': typeof AuthRoutesNovoEcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signup' | '/completar-ec' | '/home' | '/novo-ec'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signup' | '/completar-ec' | '/home' | '/novo-ec'
  id:
    | '__root__'
    | '/'
    | '/_authRoutes'
    | '/signup'
    | '/_authRoutes/completar-ec'
    | '/_authRoutes/home'
    | '/_authRoutes/novo-ec'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoutesRouteRoute: typeof AuthRoutesRouteRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authRoutes': {
      id: '/_authRoutes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authRoutes/novo-ec': {
      id: '/_authRoutes/novo-ec'
      path: '/novo-ec'
      fullPath: '/novo-ec'
      preLoaderRoute: typeof AuthRoutesNovoEcRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/home': {
      id: '/_authRoutes/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthRoutesHomeRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/completar-ec': {
      id: '/_authRoutes/completar-ec'
      path: '/completar-ec'
      fullPath: '/completar-ec'
      preLoaderRoute: typeof AuthRoutesCompletarEcRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
  }
}

interface AuthRoutesRouteRouteChildren {
  AuthRoutesCompletarEcRoute: typeof AuthRoutesCompletarEcRoute
  AuthRoutesHomeRoute: typeof AuthRoutesHomeRoute
  AuthRoutesNovoEcRoute: typeof AuthRoutesNovoEcRoute
}

const AuthRoutesRouteRouteChildren: AuthRoutesRouteRouteChildren = {
  AuthRoutesCompletarEcRoute: AuthRoutesCompletarEcRoute,
  AuthRoutesHomeRoute: AuthRoutesHomeRoute,
  AuthRoutesNovoEcRoute: AuthRoutesNovoEcRoute,
}

const AuthRoutesRouteRouteWithChildren = AuthRoutesRouteRoute._addFileChildren(
  AuthRoutesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoutesRouteRoute: AuthRoutesRouteRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
