/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRoutesRouteRouteImport } from './routes/_authRoutes/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRoutesSalesRouteImport } from './routes/_authRoutes/sales'
import { Route as AuthRoutesPlanosETaxasRouteImport } from './routes/_authRoutes/planos-e-taxas'
import { Route as AuthRoutesNovoPlanoRouteImport } from './routes/_authRoutes/novo-plano'
import { Route as AuthRoutesNovoEcRouteImport } from './routes/_authRoutes/novo-ec'
import { Route as AuthRoutesCompletarEcRouteImport } from './routes/_authRoutes/completar-ec'
import { Route as AuthRoutesBusinessListRouteImport } from './routes/_authRoutes/business-list'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoutesRouteRoute = AuthRoutesRouteRouteImport.update({
  id: '/_authRoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoutesSalesRoute = AuthRoutesSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesPlanosETaxasRoute = AuthRoutesPlanosETaxasRouteImport.update({
  id: '/planos-e-taxas',
  path: '/planos-e-taxas',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesNovoPlanoRoute = AuthRoutesNovoPlanoRouteImport.update({
  id: '/novo-plano',
  path: '/novo-plano',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesNovoEcRoute = AuthRoutesNovoEcRouteImport.update({
  id: '/novo-ec',
  path: '/novo-ec',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesCompletarEcRoute = AuthRoutesCompletarEcRouteImport.update({
  id: '/completar-ec',
  path: '/completar-ec',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)
const AuthRoutesBusinessListRoute = AuthRoutesBusinessListRouteImport.update({
  id: '/business-list',
  path: '/business-list',
  getParentRoute: () => AuthRoutesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/business-list': typeof AuthRoutesBusinessListRoute
  '/completar-ec': typeof AuthRoutesCompletarEcRoute
  '/novo-ec': typeof AuthRoutesNovoEcRoute
  '/novo-plano': typeof AuthRoutesNovoPlanoRoute
  '/planos-e-taxas': typeof AuthRoutesPlanosETaxasRoute
  '/sales': typeof AuthRoutesSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/business-list': typeof AuthRoutesBusinessListRoute
  '/completar-ec': typeof AuthRoutesCompletarEcRoute
  '/novo-ec': typeof AuthRoutesNovoEcRoute
  '/novo-plano': typeof AuthRoutesNovoPlanoRoute
  '/planos-e-taxas': typeof AuthRoutesPlanosETaxasRoute
  '/sales': typeof AuthRoutesSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authRoutes': typeof AuthRoutesRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authRoutes/business-list': typeof AuthRoutesBusinessListRoute
  '/_authRoutes/completar-ec': typeof AuthRoutesCompletarEcRoute
  '/_authRoutes/novo-ec': typeof AuthRoutesNovoEcRoute
  '/_authRoutes/novo-plano': typeof AuthRoutesNovoPlanoRoute
  '/_authRoutes/planos-e-taxas': typeof AuthRoutesPlanosETaxasRoute
  '/_authRoutes/sales': typeof AuthRoutesSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/business-list'
    | '/completar-ec'
    | '/novo-ec'
    | '/novo-plano'
    | '/planos-e-taxas'
    | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/business-list'
    | '/completar-ec'
    | '/novo-ec'
    | '/novo-plano'
    | '/planos-e-taxas'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_authRoutes'
    | '/signup'
    | '/_authRoutes/business-list'
    | '/_authRoutes/completar-ec'
    | '/_authRoutes/novo-ec'
    | '/_authRoutes/novo-plano'
    | '/_authRoutes/planos-e-taxas'
    | '/_authRoutes/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoutesRouteRoute: typeof AuthRoutesRouteRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authRoutes': {
      id: '/_authRoutes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authRoutes/sales': {
      id: '/_authRoutes/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthRoutesSalesRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/planos-e-taxas': {
      id: '/_authRoutes/planos-e-taxas'
      path: '/planos-e-taxas'
      fullPath: '/planos-e-taxas'
      preLoaderRoute: typeof AuthRoutesPlanosETaxasRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/novo-plano': {
      id: '/_authRoutes/novo-plano'
      path: '/novo-plano'
      fullPath: '/novo-plano'
      preLoaderRoute: typeof AuthRoutesNovoPlanoRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/novo-ec': {
      id: '/_authRoutes/novo-ec'
      path: '/novo-ec'
      fullPath: '/novo-ec'
      preLoaderRoute: typeof AuthRoutesNovoEcRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/completar-ec': {
      id: '/_authRoutes/completar-ec'
      path: '/completar-ec'
      fullPath: '/completar-ec'
      preLoaderRoute: typeof AuthRoutesCompletarEcRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
    '/_authRoutes/business-list': {
      id: '/_authRoutes/business-list'
      path: '/business-list'
      fullPath: '/business-list'
      preLoaderRoute: typeof AuthRoutesBusinessListRouteImport
      parentRoute: typeof AuthRoutesRouteRoute
    }
  }
}

interface AuthRoutesRouteRouteChildren {
  AuthRoutesBusinessListRoute: typeof AuthRoutesBusinessListRoute
  AuthRoutesCompletarEcRoute: typeof AuthRoutesCompletarEcRoute
  AuthRoutesNovoEcRoute: typeof AuthRoutesNovoEcRoute
  AuthRoutesNovoPlanoRoute: typeof AuthRoutesNovoPlanoRoute
  AuthRoutesPlanosETaxasRoute: typeof AuthRoutesPlanosETaxasRoute
  AuthRoutesSalesRoute: typeof AuthRoutesSalesRoute
}

const AuthRoutesRouteRouteChildren: AuthRoutesRouteRouteChildren = {
  AuthRoutesBusinessListRoute: AuthRoutesBusinessListRoute,
  AuthRoutesCompletarEcRoute: AuthRoutesCompletarEcRoute,
  AuthRoutesNovoEcRoute: AuthRoutesNovoEcRoute,
  AuthRoutesNovoPlanoRoute: AuthRoutesNovoPlanoRoute,
  AuthRoutesPlanosETaxasRoute: AuthRoutesPlanosETaxasRoute,
  AuthRoutesSalesRoute: AuthRoutesSalesRoute,
}

const AuthRoutesRouteRouteWithChildren = AuthRoutesRouteRoute._addFileChildren(
  AuthRoutesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoutesRouteRoute: AuthRoutesRouteRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
