# Generated by Django 5.2.1 on 2026-09-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def load_new_reference_data(apps, schema_editor):
    OwnNetwork = apps.get_model("own", "OwnNetwork")
    OwnMethod = apps.get_model("own", "OwnMethod")
    OwnNetwork.objects.get_or_create(name="Default")
    OwnMethod.objects.get_or_create(name="Anticipation")


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0002_alter_ownfee_value_and_basemdr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnActivity',
            fields=[
                ('cnae', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('mcc', models.IntegerField()),
            ],
            options={
                'db_table': 'own_activities',
                'ordering': ['cnae'],
            },
        ),
        migrations.CreateModel(
            name='OwnPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('anticipation_type', models.CharField(choices=[('None', 'None'), ('Rotating', 'Rotating')], default='None', max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='own.ownactivity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_own_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_own_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'own_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnPlanFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_fees', to='own.ownfee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='own.ownplan')),
            ],
            options={
                'db_table': 'own_plan_fees',
                'constraints': [models.UniqueConstraint(fields=('plan', 'fee'), name='unique_own_plan_fee')],
            },
        ),
        migrations.RunPython(load_new_reference_data, migrations.RunPython.noop),
    ]
