# Generated by Django 5.2.1 on 2026-09-01 14:57

import django.db.models.deletion
from django.db import migrations, models


def load_baskets(apps, schema_editor):
    OwnBasket = apps.get_model("own", "OwnBasket")
    OwnBasket.objects.bulk_create([
        OwnBasket(id=117, name="Bandeira"),
        OwnBasket(id=333, name="Parcela"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0003_ownactivity_ownplan_ownplanfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnBasket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'own_baskets',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(load_baskets, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ownfee',
            name='basketName',
        ),
        migrations.AddField(
            model_name='ownplan',
            name='basketId',
            field=models.ForeignKey(db_column='basketId', default=117, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='own.ownbasket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownfee',
            name='basketId',
            field=models.ForeignKey(db_column='basketId', on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='own.ownbasket'),
        ),
    ]
