# Generated by Django 5.2.1 on 2026-09-04 15:00

import django.core.validators
import own.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0006_ownbusiness_registration_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownbusiness',
            name='registration_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REGISTERED', 'Registered'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownbusiness',
            name='signatory_cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.'), django.core.validators.MinLengthValidator(11), own.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='ownbusinesspartner',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+\\Z', 'This field must contain only digits.'), django.core.validators.MinLengthValidator(11), own.validators.validate_cpf]),
        ),
    ]
